### ISSUE TITLE
How to use a later version than mapsforge 0.8.0 with the latest (6.0.3) version of osmdroid-mapsforge?

### ISSUE THREAD

**Issue by TomasJohansson** [osmdroid/osmdroid#1265]
## Issue Type
[x] Question
[x] Bug
[x] Improvement (supporting later version of mapsforge)
[ ] Build system related
[ ] Performance
[x] Documentation

### If it's a bug, version(s) of android this affects:
All

### Version of osmdroid the issue relates to:
6.0.3
when using osmdroid-mapsforge 6.0.3 together with mapsforge 0.9+ (0.10 is currently the latest)

## Description and/or steps/code to reproduce the problem
Try to use osmdroid with mapsforge as it is documented here:
https://github.com/osmdroid/osmdroid/wiki/Mapsforge
but with the current latest versions of mapsforge and osmdroid i.e. this gradle configurations:
```gradle
    implementation 'org.osmdroid:osmdroid-android:6.0.3'
    implementation 'org.osmdroid:osmdroid-mapsforge:6.0.3'
    implementation 'org.mapsforge:mapsforge-themes:0.10.0'
    implementation 'org.mapsforge:mapsforge-map-android:0.10.0'
    implementation 'org.mapsforge:mapsforge-map:0.10.0'
```

Quote from the above documentation page:
```java
//super important to configure some of the mapsforge settings first in your activity onCreate:
MapsForgeTileSource.createInstance(this.getApplication());
```
The implementation of the above method "MapsForgeTileSource.createInstance" (in osmdroid-mapsforge version 6.0.3) will invoke this method:
org.mapsforge.map.reader.ReadBuffer.setMaximumBufferSize 
which does not exist in version 0.9.0 of mapsforge-map-reader (nor in version 0.10.0)

Therefore the result becomes:
java.lang.NoSuchMethodError: No static method setMaximumBufferSize(I)V in class Lorg/mapsforge/map/reader/ReadBuffer; or its super classes (declaration of 'org.mapsforge.map.reader.ReadBuffer'

The method ReadBuffer.setMaximumBufferSize seem to have been removed from mapsforge in september 2017:
https://github.com/mapsforge/mapsforge/commit/c755db6f8f316260a52cd4815c1b677845282349#diff-77b9f5256e13803ec9ab28654633fd5a
https://github.com/mapsforge/mapsforge/issues/994

So, obviously it is not possible to use "MapsForgeTileSource.createInstance" which is *currently* described as "super important" in the above linked documentation page.
On the other hand, that documentation may have not been updated, and maybe there is some other way to use the latest osmdroid with a later version than mapsforge 0.8.0 ?

**Comment by spyhunter99** [comment]
i think there was some work update this a while ago. the maps forge folks changed their apis around significantly i don't think i ever got it working with a 0.8 version. Something related to theme resource files IIRC

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/issues/1145

**Comment by spyhunter99** [comment]
i do have a stash of an attempt to update to 0.10.0 but it definitely didn't work and wasn't a straight forward update due to the api changes and no clear path forward

**Comment by TomasJohansson** [comment]
> i don't think i ever got it working with a 0.8 version

Do you mean osmdroid does not work properly with mapsforge 0.8 ?
Or was it a typing error i.e. you meant it works with 0.8 but you never got it working with a 0.9+ version?

**Comment by spyhunter99** [comment]
i don't remember honestly. i know have the stash for the attempt at 0.10.

**Comment by TomasJohansson** [comment]
osmdroid 6.0.1 should work with mapsforge 0.8.0 since @MKergall added that version combination into the documentation revision ea98bfb 
https://github.com/osmdroid/osmdroid/wiki/Mapsforge/_history
Of course there is no guarantee for that since docs may have bugs but there should have been a reason for those version numbers in the documentation.
(i.e. the reason should be that those two versions was actually tested together)

**Comment by MKergall** [comment]
I tested again, and I confirm that osmdroid 6.0.3 works (fine) with mapsforge 0.8.0. 

Important warning: mapsforge 0.8.0 means using mapsforge maps in v4 format (v5 format has been introduced with mapsforge 0.10.0)

Upgrading upcoming osmdroid release to mapsforge 0.10.0 would be a good point.

**Comment by monsieurtanuki** [comment]
@TomasJohansson I've just PR'ed #1275, that switches to mapsforge 0.10.0 and removes the `ReadBuffer.setMaximumBufferSize` line.
I don't know very much about MapsForge, but the little code sample I use for #1145 works.
Feel free to test it, tell us what you think, and then it will be included in the next osmdroid version.

**Comment by MKergall** [comment]
@monsieurtanuki Thanks a lot!

**Comment by monsieurtanuki** [comment]
@MKergall Had time to test it? Should I merge, then?

**Comment by TomasJohansson** [comment]
> I don't know very much about MapsForge, but the little code sample I use for #1145 works.
> Feel free to test it, tell us what you think, and then it will be included in the next osmdroid version.

Okay I have also tested it with my tablet and it seems to work. 
A bit suprprising though that it worked with such a small change considering what was written above regarding it wasn't a straight forward update due to the api changes and no clear path forward.
Anyway I can close this issue now.

**Comment by monsieurtanuki** [comment]
@TomasJohansson Thank you for your test, in first approach it's good enough for a "go!". Is that a 100% perfect update path: I don't think so, but that will do for the moment.
If later you find issues with this osmdroid vs. mapsforge 0.10.0 combination, that will be dealt with in new issues.

**Comment by k3b** [comment]
Same situation here:

try to use mapsforge 0.10.0 with org.osmdroid:osmdroid-mapsforge:6.0.3:

As a workaround I tried to use proguard-rues.pro to remove the call as explainded in https://www.guardsquare.com/proguard/manual/examples#logging with 

   -assumenosideeffects class org.mapsforge.map.reader.ReadBuffer { 
         public void setMaximumBufferSize(...); }

but got 

	Warning: org.osmdroid.mapsforge.MapsForgeTileSource: can't find referenced method 
	'void setMaximumBufferSize(int)' in program class org.mapsforge.map.reader.ReadBuffer
	Warning: there were 1 unresolved references to program class members.
			 Your input classes appear to be inconsistent.
			 You may need to recompile the code.

Any idea how to fix this with proguard while the next osmdroid-release 0.6.0.4 with https://github.com/osmdroid/osmdroid/issues/1265 (or later) is not available yet?

**Comment by monsieurtanuki** [comment]
Disclaimer: I'm a bit confused in general with gradle stuff.

If the problem is only at run time, that would make sense to:
* copy the 3 "osmdroid x MapsForge" classes (`MapsForgeTileModuleProvider`, `MapsForgeTileProvider` and `MapsForgeTileSource`) into your project (latest version available in osmdroid)
* use whatever version of MapsForge is relevant for your app
* use the 3 copied classes, that don't include the `ReadBuffer.setMaximumBufferSize` part

**Comment by k3b** [comment]
the problem occurs when obfuscating which also warns about unresolved dependencies.

you solution is simple and effective. i will try it.

thanks a lot
